app:
  tracking:
    distance: 0.1
    timeout: 3600
  share:
    url: 'https://foodspots.me/?utm_source=facebook&utm_medium=dm&utm_campaign=invite'
  pins:
    default_image: 'https://s3.amazonaws.com/dinderapp/pins/Mes%20en%20vork.jpg?'
